services:
  postgres:
    image: postgres:15
    container_name: coffee-shop-db
    environment:
      POSTGRES_DB: coffee_shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
